// generated by Mathlified on 5/15/2025, 5:29:12 PM
export interface NavNode {
  name: string;
  slug: string;
  fileSlug: string;
  children?: NavNode[];
}
export const notesNav: NavNode = {
  name: "Notes",
  slug: "/notes",
  fileSlug: "/1_notes",
  children: [
    {
      name: "Calculus",
      slug: "/notes/calculus",
      fileSlug: "/1_notes/calculus",
    },
    {
      name: "Functions and graphs",
      slug: "/notes/functions-and-graphs",
      fileSlug: "/1_notes/functions-and-graphs",
      children: [
        {
          name: "1.1 Review of functions",
          slug: "/notes/functions-and-graphs/1-review",
          fileSlug: "/1_notes/functions-and-graphs/1-review",
        },
        {
          name: "1.2 Basic classes of functions",
          slug: "/notes/functions-and-graphs/2-basic-classes-of-functions",
          fileSlug:
            "/1_notes/functions-and-graphs/2-basic-classes-of-functions",
        },
      ],
    },
    {
      name: "Limits",
      slug: "/notes/limits",
      fileSlug: "/1_notes/limits",
      children: [
        {
          name: "Introduction",
          slug: "/notes/limits/introduction",
          fileSlug: "/1_notes/limits/0_introduction",
        },
        {
          name: "2.1 A preview of calculus",
          slug: "/notes/limits/1-a-preview-of-calculus",
          fileSlug: "/1_notes/limits/1-a-preview-of-calculus",
        },
        {
          name: "Chapter review",
          slug: "/notes/limits/chapter-review",
          fileSlug: "/1_notes/limits/chapter-review",
          children: [
            {
              name: "Review Exercises",
              slug: "/notes/limits/chapter-review/review-exercises",
              fileSlug: "/1_notes/limits/chapter-review/review-exercises",
            },
          ],
        },
      ],
    },
  ],
};
export const questionsNav: NavNode = {
  name: "Questions",
  slug: "/questions",
  fileSlug: "/2_questions",
  children: [
    {
      name: "Elementary algebra 2e",
      slug: "/questions/elementary-algebra-2e",
      fileSlug: "/2_questions/0_elementary-algebra-2e",
    },
    {
      name: "Use the language of algebra",
      slug: "/questions/1-2-use-the-language-of-algebra",
      fileSlug: "/2_questions/1-2-use-the-language-of-algebra",
    },
    {
      name: "Add integers",
      slug: "/questions/1-3-add-integers",
      fileSlug: "/2_questions/1-3-add-integers",
    },
    {
      name: "Solving linear equations",
      slug: "/questions/2-solving-linear-equations",
      fileSlug: "/2_questions/2-solving-linear-equations",
    },
  ],
};
export const printoutsNav: NavNode = {
  name: "Printouts",
  slug: "/printouts",
  fileSlug: "/3_printouts",
  children: [
    {
      name: "Local setup",
      slug: "/printouts/local-setup",
      fileSlug: "/3_printouts/0_local-setup",
    },
    {
      name: "Defining the derivative",
      slug: "/printouts/defining-the-derivative",
      fileSlug: "/3_printouts/1_defining-the-derivative",
    },
    {
      name: "Differentiation rules",
      slug: "/printouts/differentiation-rules",
      fileSlug: "/3_printouts/2_differentiation-rules",
    },
  ],
};
export const quizNav: NavNode = {
  name: "Quiz",
  slug: "/quiz",
  fileSlug: "/4_quiz",
  children: [
    {
      name: "Sitewide customization",
      slug: "/quiz/sitewide-customization",
      fileSlug: "/4_quiz/0a_sitewide-customization",
    },
    {
      name: "Customize collections",
      slug: "/quiz/customize-collections",
      fileSlug: "/4_quiz/0b_customize-collections",
    },
    {
      name: "Arithmetic",
      slug: "/quiz/1-arithmetic",
      fileSlug: "/4_quiz/1-arithmetic",
    },
    { name: "Algebra", slug: "/quiz/2-algebra", fileSlug: "/4_quiz/2-algebra" },
  ],
};
export const examNav: NavNode = {
  name: "Exam",
  slug: "/exam",
  fileSlug: "/5_exam",
  children: [
    {
      name: "Customizing pdfs",
      slug: "/exam/customizing-pdfs",
      fileSlug: "/5_exam/0_customizing-pdfs",
    },
    { name: "Exam", slug: "/exam/exam", fileSlug: "/5_exam/exam" },
  ],
};
export const metaNav: NavNode = {
  name: "Meta",
  slug: "/meta",
  fileSlug: "/271828_meta",
  children: [
    {
      name: "Features",
      slug: "/meta/features",
      fileSlug: "/271828_meta/0_features",
    },
    {
      name: "Changelog",
      slug: "/meta/changelog",
      fileSlug: "/271828_meta/1_changelog",
    },
    {
      name: "Roadmap",
      slug: "/meta/roadmap",
      fileSlug: "/271828_meta/2_roadmap",
    },
    {
      name: "Credits",
      slug: "/meta/credits",
      fileSlug: "/271828_meta/3_credits",
    },
  ],
};
export const notesSequential: { name: string; slug: string }[] = [
  { name: "Calculus", slug: "/notes/calculus" },
  {
    name: "1.1 Review of functions",
    slug: "/notes/functions-and-graphs/1-review",
  },
  {
    name: "1.2 Basic classes of functions",
    slug: "/notes/functions-and-graphs/2-basic-classes-of-functions",
  },
  { name: "Introduction", slug: "/notes/limits/introduction" },
  {
    name: "2.1 A preview of calculus",
    slug: "/notes/limits/1-a-preview-of-calculus",
  },
  {
    name: "Review Exercises",
    slug: "/notes/limits/chapter-review/review-exercises",
  },
];
export const questionsSequential: { name: string; slug: string }[] = [
  { name: "Elementary algebra 2e", slug: "/questions/elementary-algebra-2e" },
  {
    name: "Use the language of algebra",
    slug: "/questions/1-2-use-the-language-of-algebra",
  },
  { name: "Add integers", slug: "/questions/1-3-add-integers" },
  {
    name: "Solving linear equations",
    slug: "/questions/2-solving-linear-equations",
  },
];
export const printoutsSequential: { name: string; slug: string }[] = [
  { name: "Local setup", slug: "/printouts/local-setup" },
  {
    name: "Defining the derivative",
    slug: "/printouts/defining-the-derivative",
  },
  { name: "Differentiation rules", slug: "/printouts/differentiation-rules" },
];
export const quizSequential: { name: string; slug: string }[] = [
  { name: "Sitewide customization", slug: "/quiz/sitewide-customization" },
  { name: "Customize collections", slug: "/quiz/customize-collections" },
  { name: "Arithmetic", slug: "/quiz/1-arithmetic" },
  { name: "Algebra", slug: "/quiz/2-algebra" },
];
export const examSequential: { name: string; slug: string }[] = [
  { name: "Customizing pdfs", slug: "/exam/customizing-pdfs" },
  { name: "Exam", slug: "/exam/exam" },
];
export const metaSequential: { name: string; slug: string }[] = [
  { name: "Features", slug: "/meta/features" },
  { name: "Changelog", slug: "/meta/changelog" },
  { name: "Roadmap", slug: "/meta/roadmap" },
  { name: "Credits", slug: "/meta/credits" },
];
export const nav = [
  notesNav,
  questionsNav,
  printoutsNav,
  quizNav,
  examNav,
  metaNav,
];
export const sequentialNav = [
  ...notesSequential,
  ...questionsSequential,
  ...printoutsSequential,
  ...quizSequential,
  ...examSequential,
  ...metaSequential,
];
