import katex from 'katex';
/**
 * Renders inline math
 * 
 * Takes a TeX expression and outputs a HTML string for the rendered math
 * 
 * @param x TeX expression to be rendered
 * @param options defaults to `{wrap: false, throwOnError: false}`.
 * `wrap` is a custom option where the default `wrap===false` disables line breaks by default by adding braces to the TeX expression.
 * All KaTeX options are supported, and with the exception of `throwOnError` are left as default
 * 
 * @returns HTML string generated by KaTeX representing inline math
 * 
 * With default options, is equivalent to calling `katex.renderToString('{'+x+'}', {throwOnError: false})
 */
export function math(x: string, options?: KatexOptionsInline) {
  options = {wrap: false, throwOnError: false, ...options};
  const xString = options.wrap ? x : `{${x}}`
  return katex.renderToString(xString, options);
}

interface KatexOptionsInline extends katex.KatexOptions {
  wrap?: boolean
}