import { display, type KatexOptionsDisplay } from './display';

/**
 * Renders align environment in displayed mode
 *
 * Takes a TeX expression and outputs a HTML string for the rendered math in displayed mode
 *
 * @param x TeX expression to be rendered
 * @param options defaults to `{overflowAuto: true, throwOnError: false}`.
 * overflowAuto is a custom option where the default `overflowAuto===true` wraps the generated HTML in a container with `style="overflow-x:auto;"`
 * All KaTeX options are supported, and with the exception of `throwOnError` and `displayMode` are left as default
 *
 * @returns HTML string generated by KaTeX representing displayed math
 *
 * With default options, is equivalent to
 * wrapping x with `\\begin{align} ... \\end{align}`, calling
 * `katex.renderToString(x, {throwOnError: false, displayMode: true})
 * and wrapping it in a container with `style="overflow-x:auto;"`
 */
export function align(x: string, options?: KatexOptionsDisplay) {
	options = {
		overflowAuto: true,
		throwOnError: false,
		displayMode: true,
		...options,
	};
	return displayEnvironment('align', x, options);
}

/**
 * Renders align* environment in displayed mode
 *
 * Takes a TeX expression and outputs a HTML string for the rendered math in displayed mode
 *
 * @param x TeX expression to be rendered
 * @param options defaults to `{overflowAuto: true, throwOnError: false}`.
 * overflowAuto is a custom option where the default `overflowAuto===true` wraps the generated HTML in a container with `style="overflow-x:auto;"`
 * All KaTeX options are supported, and with the exception of `throwOnError` and `displayMode` are left as default
 *
 * @returns HTML string generated by KaTeX representing displayed math
 *
 * With default options, is equivalent to
 * wrapping x with `\\begin{align*} ... \\end{align*}`, calling
 * `katex.renderToString(x, {throwOnError: false, displayMode: true})
 * and wrapping it in a container with `style="overflow-x:auto;"`
 */
export function alignStar(x: string, options?: KatexOptionsDisplay) {
	options = {
		overflowAuto: true,
		throwOnError: false,
		displayMode: true,
		...options,
	};
	return displayEnvironment('align*', x, options);
}

/**
 * Renders alignat environment in displayed mode
 *
 * Takes a TeX expression and outputs a HTML string for the rendered math in displayed mode
 *
 * @param x TeX expression to be rendered
 * @param pairs number of r/l column pairs
 * @param options defaults to `{overflowAuto: true, throwOnError: false}`.
 * overflowAuto is a custom option where the default `overflowAuto===true` wraps the generated HTML in a container with `style="overflow-x:auto;"`
 * All KaTeX options are supported, and with the exception of `throwOnError` and `displayMode` are left as default
 *
 * @returns HTML string generated by KaTeX representing displayed math
 *
 * With default options, is equivalent to
 * wrapping x with `\\begin{alignat} ... \\end{alignat}`, calling
 * `katex.renderToString(x, {throwOnError: false, displayMode: true})
 * and wrapping it in a container with `style="overflow-x:auto;"`
 */
export function alignat(x: string, pairs: number, options?: KatexOptionsDisplay) {
	const alignatOptions = {
		overflowAuto: true,
		throwOnError: false,
		displayMode: true,
		postBegin: `{${pairs}}`,
		...options,
	};
	return displayEnvironment('alignat', x, alignatOptions);
}

/**
 * Renders alignat* environment in displayed mode
 *
 * Takes a TeX expression and outputs a HTML string for the rendered math in displayed mode
 *
 * @param x TeX expression to be rendered
 * @param pairs number of r/l column pairs
 * @param options defaults to `{overflowAuto: true, throwOnError: false}`.
 * overflowAuto is a custom option where the default `overflowAuto===true` wraps the generated HTML in a container with `style="overflow-x:auto;"`
 * All KaTeX options are supported, and with the exception of `throwOnError` and `displayMode` are left as default
 *
 * @returns HTML string generated by KaTeX representing displayed math
 *
 * With default options, is equivalent to
 * wrapping x with `\\begin{alignat*} ... \\end{alignat*}`, calling
 * `katex.renderToString(x, {throwOnError: false, displayMode: true})
 * and wrapping it in a container with `style="overflow-x:auto;"`
 */
export function alignatStar(x: string, pairs: number, options?: KatexOptionsDisplay) {
	const alignatOptions = {
		overflowAuto: true,
		throwOnError: false,
		displayMode: true,
		postBegin: `{${pairs}}`,
		...options,
	};
	return displayEnvironment('alignat*', x, alignatOptions);
}

/**
 * Renders gather environment in displayed mode
 *
 * Takes a TeX expression and outputs a HTML string for the rendered math in displayed mode
 *
 * @param x TeX expression to be rendered
 * @param options defaults to `{overflowAuto: true, throwOnError: false}`.
 * overflowAuto is a custom option where the default `overflowAuto===true` wraps the generated HTML in a container with `style="overflow-x:auto;"`
 * All KaTeX options are supported, and with the exception of `throwOnError` and `displayMode` are left as default
 *
 * @returns HTML string generated by KaTeX representing displayed math
 *
 * With default options, is equivalent to
 * wrapping x with `\\begin{gather} ... \\end{gather}`, calling
 * `katex.renderToString(x, {throwOnError: false, displayMode: true})
 * and wrapping it in a container with `style="overflow-x:auto;"`
 */
export function gather(x: string, options?: KatexOptionsDisplay) {
	options = {
		overflowAuto: true,
		throwOnError: false,
		displayMode: true,
		...options,
	};
	return displayEnvironment('gather', x, options);
}

/**
 * Renders gather* environment in displayed mode
 *
 * Takes a TeX expression and outputs a HTML string for the rendered math in displayed mode
 *
 * @param x TeX expression to be rendered
 * @param options defaults to `{overflowAuto: true, throwOnError: false}`.
 * overflowAuto is a custom option where the default `overflowAuto===true` wraps the generated HTML in a container with `style="overflow-x:auto;"`
 * All KaTeX options are supported, and with the exception of `throwOnError` and `displayMode` are left as default
 *
 * @returns HTML string generated by KaTeX representing displayed math
 *
 * With default options, is equivalent to
 * wrapping x with `\\begin{gather*} ... \\end{gather*}`, calling
 * `katex.renderToString(x, {throwOnError: false, displayMode: true})
 * and wrapping it in a container with `style="overflow-x:auto;"`
 */
export function gatherStar(x: string, options?: KatexOptionsDisplay) {
	options = {
		overflowAuto: true,
		throwOnError: false,
		displayMode: true,
		...options,
	};
	return displayEnvironment('gather*', x, options);
}

/**
 * Renders equation environment in displayed mode
 *
 * Takes a TeX expression and outputs a HTML string for the rendered math in displayed mode
 *
 * @param x TeX expression to be rendered
 * @param options defaults to `{overflowAuto: true, throwOnError: false}`.
 * overflowAuto is a custom option where the default `overflowAuto===true` wraps the generated HTML in a container with `style="overflow-x:auto;"`
 * All KaTeX options are supported, and with the exception of `throwOnError` and `displayMode` are left as default
 *
 * @returns HTML string generated by KaTeX representing displayed math
 *
 * With default options, is equivalent to
 * wrapping x with `\\begin{equation} ... \\end{equation}`, calling
 * `katex.renderToString(x, {throwOnError: false, displayMode: true})
 * and wrapping it in a container with `style="overflow-x:auto;"`
 */
export function equation(x: string, options?: KatexOptionsDisplay) {
	options = {
		overflowAuto: true,
		throwOnError: false,
		displayMode: true,
		...options,
	};
	return displayEnvironment('equation', x, options);
}

/**
 * Renders equation* environment in displayed mode
 *
 * Takes a TeX expression and outputs a HTML string for the rendered math in displayed mode
 *
 * @param x TeX expression to be rendered
 * @param options defaults to `{overflowAuto: true, throwOnError: false}`.
 * overflowAuto is a custom option where the default `overflowAuto===true` wraps the generated HTML in a container with `style="overflow-x:auto;"`
 * All KaTeX options are supported, and with the exception of `throwOnError` and `displayMode` are left as default
 *
 * @returns HTML string generated by KaTeX representing displayed math
 *
 * With default options, is equivalent to
 * wrapping x with `\\begin{equation*} ... \\end{equation*}`, calling
 * `katex.renderToString(x, {throwOnError: false, displayMode: true})
 * and wrapping it in a container with `style="overflow-x:auto;"`
 */
export function equationStar(x: string, options?: KatexOptionsDisplay) {
	options = {
		overflowAuto: true,
		throwOnError: false,
		displayMode: true,
		...options,
	};
	return displayEnvironment('equation*', x, options);
}

export const eqn = equation;
export const eqnStar = equationStar;

function displayEnvironment(env: string, x: string, options?: KatexEnvironmentOptions) {
	options = {
		overflowAuto: true,
		throwOnError: false,
		displayMode: true,
		postBegin: '',
		...options,
	};
	return display(
		`\\begin{${env}}${options.postBegin}
    ${x}
  \\end{${env}}`,
		options,
	);
}

interface KatexEnvironmentOptions extends KatexOptionsDisplay {
	postBegin?: string;
}
